### ISSUE TITLE
[FEAT] Full config BIG-IP migrations to v17.1

### ISSUE THREAD

**Issue by pfrosa49165** [f5devcentral/f5-journeys#100]
when will f5-journeys be able to convert ucs to 17.1?

**Comment by f5-purc** [comment]
F5-Journeys will support a conversion of an ucs to 17.1 shortly after BIG-IP v17.1 is certified on F5OS. Please follow the communications once it's released.

**Comment by pfrosa49165** [comment]
The BIG-IP v17.1 version should already be certified for F5OS because it is already available for download at my.f5.com. I have already installed it on an r2800 device BIGIP-17.1.0-0.0.16.ALL-F5OS.qcow2.zip.bundle
