### ISSUE TITLE
Bug in session name of Big-Ip full migration 

### ISSUE THREAD

**Issue by Rojin-dumre** [f5devcentral/f5-journeys#101]
I was getting this error when i tried to enter session-name under big-ip full migration:
s.detail[Object.keys(...)[0]].join is not a function

which to my knowledge is a simple javascript bug

This happened when i ran the containers by cloning the repo. However everything seemed to work when i ran the containers from the latest release file. I dont know if it was just the matter of reinstalling the containers. Thought you guys should know about it.

**Comment by f5-purc** [comment]
Is this reproducible?

**Comment by jba3126tsys** [comment]
@f5-purc I'm getting the same error.  I too had to clone the repo due to security constraints.

**Comment by jba3126tsys** [comment]
> I was getting this error when i tried to enter session-name under big-ip full migration: s.detail[Object.keys(...)[0]].join is not a function
> 
> which to my knowledge is a simple javascript bug
> 
> This happened when i ran the containers by cloning the repo. However everything seemed to work when i ran the containers from the latest release file. I dont know if it was just the matter of reinstalling the containers. Thought you guys should know about it.

Did you figure out the issue and more importantly did you find a resolution?

**Comment by jba3126tsys** [comment]
> I'm getting the same error, so I would say yes. I also had to clone the repo due to security constraints.

I'm getting the same error, so I would say yes. I also had to clone the repo due to security constraints.

**Comment by Grisha-L** [comment]
Hi,
I've stumbled upon the same issue, was able to solve it by specifying postgres image version:
`postgres:16-alpine`
Hope this helps.

**Comment by jba3126tsys** [comment]
I added this to the yaml file and got an error when trying to start up.  It's like with the version tag it is trying to go out to the registry.

![2024-02-08 11_07_58-Docker-Postgres-Version-Yaml](https://github.com/f5devcentral/f5-journeys/assets/54550032/a1e56c26-b5f7-490e-91c5-268abe2ad29b)


![2024-02-08 11_07_58-Docker-Postgres-Error](https://github.com/f5devcentral/f5-journeys/assets/54550032/10c23b36-c680-4244-a18e-974788d3a27e)

**Comment by rmaliszewskif5** [comment]
> @Grisha-L I added this to the yaml file and got an error when trying to start up. It's like with the version tag it is trying to go out to the registry.
> 
> ![2024-02-08 11_07_58-Docker-Postgres-Version-Yaml](https://private-user-images.githubusercontent.com/54550032/303403373-a1e56c26-b5f7-490e-91c5-268abe2ad29b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgxODgsIm5iZiI6MTcwNzcyNzg4OCwicGF0aCI6Ii81NDU1MDAzMi8zMDM0MDMzNzMtYTFlNTZjMjYtYjVmNy00OTBlLTkxYzUtMjY4YWJlMmFkMjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Y2QzNjNkZGQ2OWQwZDdlZjdiMTgzMzEwYjliZmZlOTk2MTkwZWM1YThjMmJkMDFhOTk4YTdiNjY1NGJiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.morvbAdxXfMFpbx-CwUjfJ4O7P7OGZrIlX2VqvBZPu0)
> 
> ![2024-02-08 11_07_58-Docker-Postgres-Error](https://private-user-images.githubusercontent.com/54550032/303402498-10c23b36-c680-4244-a18e-974788d3a27e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgxODgsIm5iZiI6MTcwNzcyNzg4OCwicGF0aCI6Ii81NDU1MDAzMi8zMDM0MDI0OTgtMTBjMjNiMzYtYzY4MC00MjQ0LWExOGUtOTc0Nzg4ZDNhMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODRiN2EwYzk0MGI3ODUzYTQxM2U0YjRiODRhYWY5NWQ1MmZiYzBhY2UwMDM3YjBjNTdjYjY0YjU3MTI0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GCfmCdDTWWc4h4rGFwxobcWRONc_v1BXIFpq3t4sM-I)

Thanks @jba3126tsys for the suggestion. I applied the tags to all containers in docker-compose file. It should work now, I tested the fix and I can't reproduce the issue anymore.

**Comment by rmaliszewskif5** [comment]
> Hi, I've stumbled upon the same issue, was able to solve it by specifying postgres image version: `postgres:16-alpine` Hope this helps.

Thanks for a suggestion. I added tags to all the containers (with Debian images, not Alpine). It's up on GitHub.


> @Grisha-L I added this to the yaml file and got an error when trying to start up. It's like with the version tag it is trying to go out to the registry.
> 
> ![2024-02-08 11_07_58-Docker-Postgres-Version-Yaml](https://private-user-images.githubusercontent.com/54550032/303403373-a1e56c26-b5f7-490e-91c5-268abe2ad29b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgxODgsIm5iZiI6MTcwNzcyNzg4OCwicGF0aCI6Ii81NDU1MDAzMi8zMDM0MDMzNzMtYTFlNTZjMjYtYjVmNy00OTBlLTkxYzUtMjY4YWJlMmFkMjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Y2QzNjNkZGQ2OWQwZDdlZjdiMTgzMzEwYjliZmZlOTk2MTkwZWM1YThjMmJkMDFhOTk4YTdiNjY1NGJiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.morvbAdxXfMFpbx-CwUjfJ4O7P7OGZrIlX2VqvBZPu0)
> 
> ![2024-02-08 11_07_58-Docker-Postgres-Error](https://private-user-images.githubusercontent.com/54550032/303402498-10c23b36-c680-4244-a18e-974788d3a27e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgxODgsIm5iZiI6MTcwNzcyNzg4OCwicGF0aCI6Ii81NDU1MDAzMi8zMDM0MDI0OTgtMTBjMjNiMzYtYzY4MC00MjQ0LWExOGUtOTc0Nzg4ZDNhMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODRiN2EwYzk0MGI3ODUzYTQxM2U0YjRiODRhYWY5NWQ1MmZiYzBhY2UwMDM3YjBjNTdjYjY0YjU3MTI0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GCfmCdDTWWc4h4rGFwxobcWRONc_v1BXIFpq3t4sM-I)

Sorry @jba3126tsys for previous tag, I pressed the wrong button. Regarding your issue, are you behind a corporate proxy? Seems like a problem with a proxy configuration on either side. 

PS: Stay tuned for an update with air-gapped installation and a bundle downloadable from both GitHub and MyF5 downloads. It should be up within few days.

**Comment by rmaliszewskif5** [comment]
I had a chat with another engineer who was able to reproduce the issue after a "fix". The problem indeed lies in Postgresql database which is unable to migrate properly between versions. The fact that it worked for @Grisha-L with a tag was because it was most likely the version that was pulled previously under `latest` tag and there were no problems with migrating data between different Postgres versions.

The solution is to remove working directory specified in .env file under `WORKING_DIRECTORY` (by default `/tmp/journeys`). **This will remove all previous sessions** but will allow database to spin up with fresh environment.

**Comment by jba3126tsys** [comment]
> I had a chat with another engineer who was able to reproduce the issue after a "fix". The problem indeed lies in Postgresql database which is unable to migrate properly between versions. The fact that it worked for @Grisha-L with a tag was because it was most likely the version that was pulled previously under `latest` tag and there were no problems with migrating data between different Postgres versions.
> 
> The solution is to remove working directory specified in .env file under `WORKING_DIRECTORY` (by default `/tmp/journeys`). **This will remove all previous sessions** but will allow database to spin up with fresh environment.

Shutting down the docker containers, deleting the /tmp/journeys folder, starting them back up resolved my issue!

**Comment by jba3126tsys** [comment]
> > Hi, I've stumbled upon the same issue, was able to solve it by specifying postgres image version: `postgres:16-alpine` Hope this helps.
> 
> Thanks for a suggestion. I added tags to all the containers (with Debian images, not Alpine). It's up on GitHub.
> 
> > @Grisha-L I added this to the yaml file and got an error when trying to start up. It's like with the version tag it is trying to go out to the registry.
> > ![2024-02-08 11_07_58-Docker-Postgres-Version-Yaml](https://private-user-images.githubusercontent.com/54550032/303403373-a1e56c26-b5f7-490e-91c5-268abe2ad29b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgxODgsIm5iZiI6MTcwNzcyNzg4OCwicGF0aCI6Ii81NDU1MDAzMi8zMDM0MDMzNzMtYTFlNTZjMjYtYjVmNy00OTBlLTkxYzUtMjY4YWJlMmFkMjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Y2QzNjNkZGQ2OWQwZDdlZjdiMTgzMzEwYjliZmZlOTk2MTkwZWM1YThjMmJkMDFhOTk4YTdiNjY1NGJiMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.morvbAdxXfMFpbx-CwUjfJ4O7P7OGZrIlX2VqvBZPu0)
> > ![2024-02-08 11_07_58-Docker-Postgres-Error](https://private-user-images.githubusercontent.com/54550032/303402498-10c23b36-c680-4244-a18e-974788d3a27e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgxODgsIm5iZiI6MTcwNzcyNzg4OCwicGF0aCI6Ii81NDU1MDAzMi8zMDM0MDI0OTgtMTBjMjNiMzYtYzY4MC00MjQ0LWExOGUtOTc0Nzg4ZDNhMjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA4NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODRiN2EwYzk0MGI3ODUzYTQxM2U0YjRiODRhYWY5NWQ1MmZiYzBhY2UwMDM3YjBjNTdjYjY0YjU3MTI0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GCfmCdDTWWc4h4rGFwxobcWRONc_v1BXIFpq3t4sM-I)
> 
> Sorry @jba3126tsys for previous tag, I pressed the wrong button. Regarding your issue, are you behind a corporate proxy? Seems like a problem with a proxy configuration on either side.
-We are behind a proxy and it is definitely an issue we are actively working to request, but our challenge is Info Sec team is not keen on wide open access to a public registry.
> 
> PS: Stay tuned for an update with air-gapped installation and a bundle downloadable from both GitHub and MyF5 downloads. It should be up within few days.
This will be very helpful depending on how our request goes.
