### ISSUE TITLE
unable to migrate from 16.1 to 17.1

### ISSUE THREAD

**Issue by abvinodu2003** [f5devcentral/f5-journeys#102]
we are using the tool to migrate the configuration from 16.1.X to 17.1.x and when we perform the same we are encountering an error need to calrification to know is the tool supports migration from 16.1.x to 17.1.x

**Comment by f5-purc** [comment]
The tool does not support 17.1 yet, we will be releasing an update with this and other features in soon.
We currently support these versions https://github.com/f5devcentral/f5-journeys#journey-full-config-migration
