### ISSUE TITLE
[BUG] docker-compose should not expose redis port

### ISSUE THREAD

**Issue by darkrain42** [f5devcentral/f5-journeys#103]
**Describe the bug**

See #69, where I reported this previously

The docker-compose.yaml file exposes unnecessary ports to the network.  The redis port is still exposed to the network, which also causes failures when I try to run journeys on a system that already has a redis daemon running/listening.

**To Reproduce**
1. Try to run `docker-compose up -d` on a system that already has a redis instance running (listening on port 6379), or run `docker-compose up -d` and then look at the open ports on the host system.

**Expected behavior**
The minimal number of ports are exposed to the network.

docker-compose creates a local network for the containers specified.  Individual containers will be able to reach other services via DNS resolution even without the ports exported/exposed.

**Screenshots**
```
% git show-ref main
18b677792327f37c0c6a6ed7253fcfe4493bc2dc refs/heads/main
18b677792327f37c0c6a6ed7253fcfe4493bc2dc refs/remotes/origin/main
% docker-compose up -d   
f5-journeys_postgres_1 is up-to-date
f5-journeys_acc-api_1 is up-to-date
Starting f5-journeys_redis_1 ... 
f5-journeys_journeys_1 is up-to-date
Starting f5-journeys_redis_1 ... error

ERROR: for f5-journeys_redis_1  Cannot start service redis: driver failed programming external connectivity on endpoint f5-journeys_redis_1 (6a40791ac56e286099b28915dc0358b79ea9dffb5175d83b666a3906aaf75055): Error starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use

ERROR: for redis  Cannot start service redis: driver failed programming external connectivity on endpoint f5-journeys_redis_1 (6a40791ac56e286099b28915dc0358b79ea9dffb5175d83b666a3906aaf75055): Error starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Context**
- Please specify, app version: v3.3.5
Current main commit (18b677792327f37c0c6a6ed7253fcfe4493bc2dc)

**Comment by f5-purc** [comment]
Filed for internal tracking: MBIPMP-19497

**Comment by wojtek0806** [comment]
fixed with: https://github.com/f5devcentral/f5-journeys/commit/d99a50d6b0b6603c47ea6dd27df3c0192199fdac
