### ISSUE TITLE
[BUG]  VLAN names when over 32 characters are nut supported on tenant

### ISSUE THREAD

**Issue by rafnizw** [f5devcentral/f5-journeys#105]
**Describe the bug**
VLAN names when over 32 characters are nut supported on tenant
Refence: https://my.f5.com/manage/s/article/K16539386

**To Reproduce**
Have a bigip tenant provisioned on a rSeries platform.
Add a vlan: <Name-must-be more thant 31 characters> with any ID:
Add the VLAN to the tenant 
Login to tenant and check VLANS (empty vlan name will be presented)

**Expected behavior**
Once Vlan with the name over 32 characters is added at host lever it should display the same name at tenant level

**Context**
- rSeries version lover than 15.x

Current workaround:
Manually edit tenant VLAN on bigip.conf before or after migration

**Comment by azahajkiewicz** [comment]
This is a VELOS issue. Closing, as Journeys team can't do much about it.
