### ISSUE TITLE
[BUG] "01020036.3: The requested device group...was not found", but that device group is not in the new bigip_base.conf file

### ISSUE THREAD

**Issue by jxadams** [f5devcentral/f5-journeys#106]
When running Journeys, at the Verify & Edit Configuration step, I get "01020036.3: The requested device group (/Common/device-failover-group) was not found. Unexpected Error: Validating configuration process failed". I'm not sure where this error is coming from, as that device group is not found anywhere in the new configuration files.

Run up to Verify & Edit configuration. Click Run and Run again. View the log.

I expected this to pass, as I'd accepted all the remediations in the previous screens.

I don't find a version number for Journeys.

I'm migrating from 15.1.4 to 17.1.0.

**Comment by azahajkiewicz** [comment]
Please open an SR ticket and upload the problematic UCS file for investigation.

https://www.f5.com/services/support

**Comment by wojtek0806** [comment]
Please retest with the latest 4.1.0 version (rebuild from scratch) and open a new issue using appropriate template providing sufficent data.
