### ISSUE TITLE
[BUG] Customer removes DeviceGroup via BIG-IP Config utility, but still gets DeviceGroup error in JOURNEYS

### ISSUE THREAD

**Issue by maranianf5** [f5devcentral/f5-journeys#108]
**Describe the bug**
The customer is attempting a migration using JOURNEYS but it is erroring stating that DeviceGroup info needs to be removed from the BIG-IP config.

**To Reproduce**
1. Customer performs migration pre-reqs to perform a UCS migration.
2. Customer "breaks" device group association in BIG-IP Config Utility prior to taking UCS backup.
3. Customer attempts to perform a UCS migration using JOURNEYS.
4. Customer gets an error performing the migration because the DeviceGroup info is still present in the config.

**Expected behavior**
JOURNEYS should not error since the customer has removed the DeviceGroup associations and references via the BIG-IP Config Utility. Customer should be able to complete their migration.

**Screenshots**
Attached 2 screenshots.

**Context**
- Please specify, app version:
Customer is running v3.3.5 of JOURNEYS. JOURNEYS is running on an x86 RHEL8 server.

-Attempting to migrate from a 2000s appliance running 15.1.5.1 to an r5900 tenant running 15.1.6.0.0.8.
[journeys.log](https://github.com/f5devcentral/f5-journeys/files/12097792/journeys.log)

JOURNEYS error logs attached. Error in reference is on line 3147 (ERROR 2023-07-17 19:25:16,022 log Internal Server Error: /sessions/3/branches/F5_Recommended_DeviceGroup_delete_objects/files/config/bigip_base.conf)

![devicegroup_error](https://github.com/f5devcentral/f5-journeys/assets/73652915/f5184bce-237d-44f0-b1b0-07216a3513c0)

![JOURNEYS_summary](https://github.com/f5devcentral/f5-journeys/assets/73652915/6a5adc46-66be-4fe3-9b24-a2c810f26db2)

**Comment by wojtek0806** [comment]
Please retest with the latest 4.1.0 version (rebuild from scratch) if the issue occurs agin, open a new issue using appropriate template providing sufficent data.
