### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peckmz** [f5devcentral/f5-journeys#111]
**Describe the bug**
Getting the following message when attempting Journeys per-app migration:  

"Some of the Virtual Servers are not compliant with AS3. Only Tenants with all green Applications/VS' can be later converted to AS3 and deployed to a BIG-IP instance.
Please drill down to uncompliant VS' and fix unsupported configurations using the editor provided."

It does not explain why or how or why the uncompliant virtuals are not compliant.  My initial suspicion was that the vs is uncompliant if not all dependancies (like policies, profiles, etc. are have been found by Journeys, but then I saw the same absence of some of the dependancies in other virtuals that were marked green/compliant.   

**To Reproduce**
1. Import a ucs file into Journeys and you will see this message as soon as the ucs is processed. 

**Expected behavior**
Some sort of explanation of what exactly Journeys was unhappy about would be nice.

**Screenshots**

**Context**
- Please specify, app version:   3.3.5

- And Platform version of the system you want to migrate.
- Migrating from iSeries to rSeries platform

**Comment by azahajkiewicz** [comment]
Journeys supports LTM migrations. If there are any dependent objects missing in the virtual servers' configuration, please open a bug for that.

Please see documentation: https://github.com/f5devcentral/f5-journeys#journey-application-service-migration
Uncompliant objects (that cannot be converted to AS3 format) should be highlighted in the editor after saving/verifying config.

**Comment by peckmz** [comment]
My question was not the missing objects.  That was just an unconfirmed guess that turned out to be false.  The issue was that Journeys marks a large number of virtual servers uncompliant without providing a reason.

**Comment by azahajkiewicz** [comment]
> My question was not the missing objects. That was just an unconfirmed guess that turned out to be false. The issue was that Journeys marks a large number of virtual servers uncompliant without providing a reason.

The reason is that f5-acc-config-converter cannot convert some of the virtual server's objects to AS3 format - there is no AS3 support for those objects.

**Comment by azahajkiewicz** [comment]
<img width="886" alt="Screenshot 2023-07-31 at 15 50 02" src="https://github.com/f5devcentral/f5-journeys/assets/73963576/138d9bfa-41ea-4555-bce6-b4b67edfb2c5">
