### ISSUE TITLE
[BUG] Journeys issue about master.lock

### ISSUE THREAD

**Issue by jimhuangtw9** [f5devcentral/f5-journeys#115]
**Describe the bug**
Hello everyone

I have recent install Journeys tool.

When I upload ucs, there have a error msg shown below.

I can't find a similar problem on the web.

Does anyone have any idea about this?

**To Reproduce**
2. Enter command '....'
3. See error

**Expected behavior**

**Screenshots**
<img width="1140" alt="截圖 2023-08-24 23 07 15" src="https://github.com/f5devcentral/f5-journeys/assets/143154240/098ea63f-51ea-4e93-9b94-09c8d7b83a1d">

**Context**
- Please specify, app version:
![截圖 2023-08-25 12 54 51](https://github.com/f5devcentral/f5-journeys/assets/143154240/6e519657-40a3-49e3-8baa-28cc1299689f)

- And Platform version of the system you want to migrate.

**Comment by jewettg** [comment]
I also am having this issue.    Only happens when I attempt to upload a UCS file for it to process.  Latest Docker (4.23.0) [120376], Compose v2.21.0-desktop.1, Engine 24.0.6, Kubernetes: v1.72.2 running on a MacBook Pro M2.

**Comment by wojtek0806** [comment]
This issue is related to #99 once that one is resolved you can retest
