### ISSUE TITLE
Rancher Desktop Support

### ISSUE THREAD

**Issue by powerballad** [f5devcentral/f5-journeys#119]
Can someone please tell me journeys supports Rancher Desktop?  I am currently using Docker Desktop, but our company is moving to Rancher Desktop.

**Comment by seamlessfirework** [comment]
I tried it a few minutes ago and it works.

**Comment by rmaliszewskif5** [comment]
Closing the issue as it looks like it's working properly on Rancher Desktop. I'm using Podman and if I'm not mistaken, both Rancher and Podman are using the same container runtime.
