### ISSUE TITLE
[BUG] - "[errno 28] no space left on device" offline mode configuration generation

### ISSUE THREAD

**Issue by shanisamis** [f5devcentral/f5-journeys#124]
**Describe the bug**
When performing an offline mode migration from BIGIP UCS to r5000 series the above error is received when generating the configuration files.

**To Reproduce**
1. Complete the offline migration using UCS to r5000

**Expected behavior**
Offline configuration files generated which can be exported for use on r5000 series appliance.

**Screenshots**
![Screenshot 2024-01-31 123401](https://github.com/f5devcentral/f5-journeys/assets/90419643/534a8e4a-ff02-4ebe-9cb6-128e2386137d)

**Context**

- Migrate BIGIP 14.1.5.6 to r5000 V17.1.x F5OS 1.5.x

**Comment by olvandeng** [comment]
Generally, the Journeys App requires more than 2xUCS file size(to store original UCS and modified UCS) in the disk, “Error 28 disk space issue” message is not reported by journeys app directly, but reported by OS, so we may need some more information to locate.

WORKING_DIRECTORY=/tmp/journeys ?
Please make sure that  directory configured as WORKING_DIRECTORY for Journeys have enough space or specifying different WORKING_DIRECTORY (with more disk space available) in Journeys .env file.

**Comment by wojtek0806** [comment]
Since there is no response I assume the issue has now been resolved, if you still have a problem, raise a new bug report following the guidelines in https://github.com/f5devcentral/f5-journeys/blob/main/SUPPORT.md. Complete the relevant bug report template with appropriate data.
