### ISSUE TITLE
[BUG] Readme Installation updates

### ISSUE THREAD

**Issue by samualblair** [f5devcentral/f5-journeys#125]
**Describe the bug**
Several elements in the Readme (installation section) are seeming dated / incorrect.

**To Reproduce**
1. Go to Readme file, preferably with markdown display support. For example view in web browser on github.com 
3. Go to installation section.

A)
Several concerns or issues with how it is now:
The Links to PerAPP is broken.
https://github.com/f5devcentral/f5-journeys/blob/readme_update_supported_migrations/PERAPP.md

B)
Document lists: 'docker compose up -d' 
Currently no reference to difference in docker-compose or docker compose.
This may not matter much, but would be very helpful to have a 'notation' for clarification, nothing to complicated needed but any expected requirement could be listed.

C)
Example command for viewing existing certificate lists:
'docker logs f5-journeys_journeys_1 2>&1 | grep 'BEGIN CERTIFICATE''

But based on following these instructions it seems it likely should be (-1 not _1):
'docker logs f5-journeys-journeys-1 2>&1 | grep 'BEGIN CERTIFICATE''

If there is any expectation that this would vary between systems (other than running a second instance which may have -2) then perhaps a 'note' section just indicating to the user to check 'docker ps' or something to verify name is as example lists.

**Expected behavior**
Directions work as expected whenever possible.
No broken links (possibly old information no longer needed).

**Comment by zhang-shengping** [comment]
> **Describe the bug** Several elements in the Readme (installation section) are seeming dated / incorrect.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Readme file, preferably with markdown display support. For example view in web browser on github.com
> 2. Go to installation section.
> 
> A) Several concerns or issues with how it is now: The Links to PerAPP is broken. https://github.com/f5devcentral/f5-journeys/blob/readme_update_supported_migrations/PERAPP.md
> 
> B) Document lists: 'docker compose up -d' Currently no reference to difference in docker-compose or docker compose. This may not matter much, but would be very helpful to have a 'notation' for clarification, nothing to complicated needed but any expected requirement could be listed.
> 
> C) Example command for viewing existing certificate lists: 'docker logs f5-journeys_journeys_1 2>&1 | grep 'BEGIN CERTIFICATE''
> 
> But based on following these instructions it seems it likely should be (-1 not _1): 'docker logs f5-journeys-journeys-1 2>&1 | grep 'BEGIN CERTIFICATE''
> 
> If there is any expectation that this would vary between systems (other than running a second instance which may have -2) then perhaps a 'note' section just indicating to the user to check 'docker ps' or something to verify name is as example lists.
> 
> **Expected behavior** Directions work as expected whenever possible. No broken links (possibly old information no longer needed).

Hi, thanks for your feedback.

I have checked and confirmed the issues(a, b, and c). They still exist and should be fixed.

**Comment by olvandeng** [comment]
Opened a Task to fix: JOURNEYS-628 GitHub [BUG] Readme Installation updates #125

**Comment by wojtek0806** [comment]
fixed with release 4.2.0
