### ISSUE TITLE
error while running  docker compose up

### ISSUE THREAD

**Issue by vikaspatil1980** [f5devcentral/f5-journeys#126]
docker compose up
[+] Running 0/0
 ⠋ Container -acc-1       Creating                                                                                 0.0s
 ⠋ Container -redis-1     Creating                                                                                 0.0s
 ⠋ Container -postgres-1  Creating                                                                                 0.0s
Error response from daemon: Invalid container name (-redis-1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

**Comment by zhang-shengping** [comment]
Hello,

I used Docker Compose version v2.24.1 to check the issue.

Normally, the project name (the prefix of `<project name>-redis-1`) is the directory name of your docker compose file by default.

I am not sure of your environment, but we can avoid the problem, by using one of the solutions below:

- `export COMPOSE_PROJECT_NAME=my-project` in your system environment.
- set `COMPOSE_PROJECT_NAME=my-project` in your `.env` file.
- run `docker compose up` commnd with option `-p` to set your `project name`, such as `docker compose -p my-project up`.

**Comment by olvandeng** [comment]
Open a task to update the doc: JOURNEYS-629 error while running docker compose up #126

**Comment by wojtek0806** [comment]
I have tested the docker-compose command with the current docker-compose.yaml file and services are built ok. If the issue persists  after following this comment: https://github.com/f5devcentral/f5-journeys/issues/126#issuecomment-1982238752 open a new issue using appropriate template providing sufficent data in the template.
