### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by d-bamini** [f5devcentral/f5-journeys#128]
**Describe the bug**

**To Reproduce**
2. Enter command '....'
3. See error
Deployment stage 'Deploy UCS' failed with the exception: Extracting manifest: /var/tmp/install_all/plaintext.ucs Product : BIG-IP Platform: UCS : C109 System: Z101 Version : UCS : 15.1.5.1 System: 15.1.10.3 Edition : UCS : Point Release 1 System: Point Release 3 Hostname: UCS : old-hostname.mycompany.com System: new-Hostname.mycompany.com The system hostname is changed to old-hostname.mycompany.com Installing --full-- configuration on host old-hostname.mycompany.com Installing configuration... GETDBVAL: Lookup DB provision.restjavad.extramb GETDBVAL: Result >>>>> Unable to find variable: provision.restjavad.extramb <<<<< RU: No PRE; RU false; leave to default to 384 ATTENTION REQUIRED: Your previous configuration files have been archived, as listed below.
**Expected behavior**

**Screenshots**

**Context**
- Please specify, app version:

- And Platform version of the system you want to migrate.

**Comment by zhang-shengping** [comment]
We probably need to define exceptions and not to print the error logs from Bigip.
Cover the error detail in Journeys log file.

**Comment by wojtek0806** [comment]
Please follow our SUPPORT readme: https://github.com/f5devcentral/f5-journeys?tab=readme-ov-file#bug-reporting-and-feature-requests and open a new issue using appropriate template providing sufficent data in the template.
