### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by d-bamini** [f5devcentral/f5-journeys#133]
Deployment stage 'Deploy UCS' failed with the exception: Extracting manifest: /var/tmp/install_all/plaintext.ucs Product : BIG-IP Platform: UCS : C113 System: Z101 Version : UCS : 13.1.3.6 System: 15.1.10.3 Edition : UCS : Point Release 6 System: Point Release 3 Hostname: UCS : lb-csb-dmz-pc-01.parimutuel.fr System: lb-ctl-a.localdomain The system hostname is changed to lb-csb-dmz-pc-01.parimutuel.fr Installing --full-- configuration on host lb-csb-dmz-pc-01.parimutuel.fr Installing configuration... Running ucs_builtin_preprocess GETDBVAL: Lookup DB provision.restjavad.extramb GETDBVAL: Result >>>>> Unable to find variable: provision.restjavad.extramb <<<<< RU: No PRE; RU false; leave to default to 384 ATTENTION REQUIRED: Your previous configuration files have been archived, as listed below. If you customized any settings in these files before upgrading, you will need to manually restore those changes by using the Configuration utility or Traffic Management Shell (tmsh). Archiving /config/wa/pvsystem.conf.13.1.3.6 Archiving /config/wa/globalfragment.xml.13.1.3.6 Archiving /config/wa/pvsystem.dtd.13.1.3.6 Post-processing... usermod: no changes Reloading License and configuration - this may take a few minutes... Configuration loading error: high-config-load-failed For additional details, please see messages in /var/log/ltm WARNING: There were one or more errors detected during installation. Check the error messages and take the proper actions if needed. ERROR: UCS installation failed. Operation aborted. Unexpected Error: UCS loading process failed.

**Comment by wojtek0806** [comment]
please open issues using template and providing adequate information, open a new issue following guidelines in readme
