### ISSUE TITLE
[BUG] Error in Journeys 4.2.0 - s.detail[Object.keys(...)[0]].join is not a function

### ISSUE THREAD

**Issue by jefferympeterson** [f5devcentral/f5-journeys#138]
I could not find the issue listed.  

### Environment

I'm only at the first step in a full migration where type the session name and select next.

##### F5OS Platform and Version

```

```
##### DESTINATION BIG-IP VERSION

```

```
##### SOURCE BIG-IP VERSION

```

```

### SUMMARY

I'm only at the first step in a full migration where type the session name and select next and I get this error s.detail[Object.keys(...)[0]].join is not a function
##### STEPS TO REPRODUCE

```

```

###### Screenshots:

![image](https://github.com/user-attachments/assets/63eec960-c43c-40af-8981-fff535057243)

###### Journeys Logs:

```

```
###### Developer console output:

```

```

**Comment by rmaliszewskif5** [comment]
We would need full journeys.log if it's there, or the output of `docker-compose logs`. From screenshots, the only thing we know is that application is not working correctly for some reason, and it's probably related to the working directory, which container might not have permissions to access. This can happen sometimes and giving full write permissions to the directory usually helps. (first, remove all contents if something is there to create a clean database)

Without any logs, we are not able to identify the issue.
