### ISSUE TITLE
[BUG] Log Watcher validator fails

### ISSUE THREAD

**Issue by ravsv650** [f5devcentral/f5-journeys#20]
**Describe the bug**
When 'Log Watcher' validator is used in Full Migration it fails with the following error:
"'utf-8' codec can't decode byte 0xdf in position 5739: invalid continuation byte"

**To Reproduce**
1. In step "Deployment & Diagnostics" make sure "Log Watcher" is selected
2. Continue with migration
3. Deployment succeeds and all other validators pass but "Log Watcher" fails with the error:
"'utf-8' codec can't decode byte 0xdf in position 5739: invalid continuation byte"

**Expected behavior**
- present log entry for further inspection
OR
- present information that there were no errors found

**Screenshots**
![image](https://user-images.githubusercontent.com/62022919/143893360-08eef117-f11f-468e-b7d2-24a5b26619ef.png)

**Context**
- Please specify, app version: 3.1.0 (bigip-parser==1.0.12)

- And Platform version of the system you want to migrate.
migration from 5250 v15.1.2.1 to Velos Tenant cBIP v.15.1.4 (BIGIP-15.1.4.1-0.0.15.ALL-VELOS)

**Comment by ravsv650** [comment]
UCS file available on request

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-4996.

**Comment by KubaTaba1uga** [comment]
I was unable to reproduce the error using version 3.3.2.
@ravsv650 please upgrade your Journeys to the newest version and try again.

**Comment by zahajkiewicz** [comment]
For the future reference, if that issue happens again, please file another bug and collect internally files from destination system:

- /var/log/ltm"
- /var/log/apm"
- /var/log/gtm"
- /var/log/tmm"
- /var/log/liveinstall.log
- /var/log/asm"
- /var/log/ts/bd.log
- /var/log/ts/asm_config_server.log
- /var/log/ts/pabnagd.log
- /var/log/ts/db_upgrade.log
- /var/log/daemon.log
- /var/log/kern.log
- /var/log/messages

as well as journeys logs (session and working directory) for debugging purpose.
