### ISSUE TITLE
[BUG] VXLAN is not supported missing in System Compatibility Checks for VELOS

### ISSUE THREAD

**Issue by artgmolina** [f5devcentral/f5-journeys#22]
**Describe the bug**
During the information screen where you can read the features not supported in VELOS, VXLAN does not appear and the feature is not supported.

**Screenshots**
![image](https://user-images.githubusercontent.com/95934302/145620871-71e6267b-5781-4c5f-8ab3-b244e99ea41f.png)

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-5615.

**Comment by jszczepanskif5** [comment]
Thanks for reporting! Starting at 3.3.1 removal of VXLAN is now a subset of the 'Tunneling' issue mitigation, and will be listed in the shown parity gap list as such.
