### ISSUE TITLE
[BUG] Journeys error code display and log file issue

### ISSUE THREAD

**Issue by jgranieri22** [f5devcentral/f5-journeys#24]
**Describe the bug**
Using Journeys for New App Migration if there any AS3 failures the UI scrolling stops at a certain point and prevents the full error from being displayed.  In addition there are no log files generated when a New App Migration deployment fails.

**To Reproduce**
1. Initiated a new Journeys New App Migration
2. Select Deploy now after entering BIG-IP src/dst info along with Tenant changes 
3. AS3 returns error 
![image](https://user-images.githubusercontent.com/76064839/149020340-50386793-da99-4a3a-8452-13db7583291a.png)

**Expected behavior**
Expectation is to be able to scroll  and see the entire error within UI instead of copy/paste function and offload to text editor
Expect a log file to be generated as well with all the relevant log data

**Screenshots**
scrolling limitation of error and Log file not generated
![image](https://user-images.githubusercontent.com/76064839/149020262-2f5b170f-a606-4570-8956-bc479563a342.png)

**Context**
Src BIG-IP v13.1
Dst BIG-IP v16.1
appsvc rpm 33

- And Platform version of the system you want to migrate.

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-3999.

**Workaround:** Select the log entry from beginning to the ..., then Control+C (copy), Control+V (past) somewhere in a text editor, you should be able to see the full error message.

**Comment by scoffeyfv** [comment]
Also seeing this issue, makes AS3 troubleshooting really challenging until you figure a workaround.  Browser is Brave, in case thats relevant here.
