### ISSUE TITLE
[DOC] Update DeviceGroup description under Known parity gaps in Readme

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/f5-journeys#27]
Hello,

This is coming from Nigel, SA in EMEA, he has many people who got confused with the DeviceGroup Known parity gaps thinking device groups are not supported on VELOS.

Could we update the description for DeviceGroup in the readme file with the following:

Device Groups are fully supported on VELOS/rSeries tenants. However, when doing a UCS migration using Journeys, the device group needs to be removed from it and re-configured manually once the UCS is migrated on the target platform

Thanks & Regards,
Roman

**Comment by jszczepanski** [comment]
Done alongside 3.2.2 hotfix.
