### ISSUE TITLE
[FEAT] Explain how to upgrade Journeys App

### ISSUE THREAD

**Issue by ekampmannf5** [f5devcentral/f5-journeys#29]
**Describe the Feature**
A potential improvement for the documentation: I managed (by accident) to do an partial upgrade of the journeys app. Starting with version journeys app 3.2.0 I discovered the new journeys app version 3.2.1 on GitHub. With my limited experience I managed to update the upgrade of the journeys app itself, but I was not aware about the dependency with the f5-automation-config-converter component. Ending up with the combination journeys-app 3.2.1 und acc 1.16.0, what was an incompatible combination.

**To Reproduce**
1. I just pulled the journeys-app 3.2.1 to my local registry 
2. then I edited the docker-compose.yaml and changed the image name for the journeys-app to the new version
3. and started the containers again by sudo docker-compose up -d
4. because I was not aware about the dependencies, the acc 1.16.0 was still active becuase I did not update references in the docker-compose.yaml...

**Describe the solution you'd like**
May be trivial, but this workflow did work for me. Just tested for an subsequest update from 3.2.1 to 3.2.2:

sudo git stash
sudo git pull
sudo docker-compose pull
sudo nano docker-compose.yaml
sudo docker-compose up -d

**Screenshots**

**Context**
- Please specify, app version: journeys-app 3.2.1 and acc 1.16.0

- And Platform version of the system you want to migrate: I am using a Ubuntu VM

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-5612.
