### ISSUE TITLE
[FEAT] Big-IP Full Migration breaks HA on Target device

### ISSUE THREAD

**Issue by thicardoso** [f5devcentral/f5-journeys#31]
**Is your feature request related to a problem? Please describe.**
I was testing the Option "Big-IP Full Migration" to a brand new HA pair. The migration was partially successful. When finished the deployment, I noticed the HA was broken. During the Migration, the Hostname and all HA configuration were moved from the UCS file.

**Describe the solution you'd like**
I would like the Full migration doesn't touch configurations like HA.

**Describe alternatives you've considered**
As I was unsure if I could edit any .conf file to avoid the HA configurations and hostname to be overwritten, I didn't tray anything. 

**Additional context**

**Comment by thicardoso** [comment]
Thanks for replying.
That could be an option but I didn't have this opportunity as the targets
were already in HA when I needed to perform the migration.

Anyway I tested in lab and noticed that even migrating the UCS to a
Standalone device, old HA configurarions and hostname are moved to the
target as well. I really would like to avoid it. I'm ok if I need to edit
any .conf file.

Thanks

Thiago

Em qui., 27 de jan. de 2022 13:07, Romain Jouhannet <
***@***.***> escreveu:

**Comment by rjouhann** [comment]
Have you tried to use the config editor available within the tool?

![image](https://user-images.githubusercontent.com/25542366/152027257-57a484f7-8739-4564-9168-433dab55933d.png)

**Comment by thicardoso** [comment]
Not yet.
I will try it and let you know.

Thanks.



Em ter., 1 de fev. de 2022 15:19, Romain Jouhannet ***@***.***>
escreveu:

**Comment by azahajkiewicz** [comment]
Please re-open, if you encounter the issue.
