### ISSUE TITLE
[BUG] UCS upload unexpected error 413

### ISSUE THREAD

**Issue by asattndr** [f5devcentral/f5-journeys#36]
**Describe the bug**
I cannot upload a UCS file during "New BIG-IP Full Migration" because: "configuration loading failed" Unexpected error (code 413)

**To Reproduce**
1. Start a "New BIG-IP Full Migration"
2. Select "Upload a UCS archive"
3. Drag&Drop a v15 UCS archive: LTM or LTM&APM -  both did not work)
4. Click "Load configuration"

**Expected behavior**
Successful upload of the UCS file

**Screenshots**
![image](https://user-images.githubusercontent.com/99474835/153570526-78e436e0-98f7-488d-a783-f6b5e8543475.png)

**Context**
-tested with UCS files
vCMP Guests 15.1.4.1
Appliance 15.1.1

**Comment by azahajkiewicz** [comment]
@asattndr could you provide journeys.log from your WORKING_DIRECTORY (/tmp/journeys by default)?
A UCS  archive would be also helpful to investigate the issue.

**Comment by asattndr** [comment]
Hi,
there is no record for the time when the UCS imports failed.
I just repeated it three additional times and noticed, that: as soon as I give the new migration-session a name ("properties"-screen) and click "next" to go to the "source device"-screen, a logentry is added to journeys.jog:
WARNING 2022-02-16 13:21:39,397 log Method Not Allowed: /sessions/3/config
WARNING 2022-02-16 13:22:05,234 log Method Not Allowed: /sessions/4/config
WARNING 2022-02-16 13:25:52,319 log Method Not Allowed: /sessions/5/config
..that's all before I try to import a UCS.

When I import the UCS, the log does not get an new record.
Hope that helps.
I will reach out to our MSP so they can open a case where a UCS file can be attached.

**Comment by azahajkiewicz** [comment]
@asattndr I was able to load the UCS archive provided by you successfully within reasonable time (~1 minute) using Chrome and Firefox web browsers. 
So basically 4xx status codes means client errors. 413 in particular is "REQUEST ENTITY TOO LARGE". 
I wonder where could be a possible limitation of the filesize to transfer- JOURNEYS doesn't have an upload filesize restrictions.

Were you able to load any UCS archive?
What system are you using?

**Comment by asattndr** [comment]
Hi, we doublechecked an found a restriction on the rev-proxy we are using to request journeys. After reconfiguring the restriction I was able to load the ucs file.
Thank you for your support!
Is there any overview about journeys error codes oder the chance to include the info "request entity too large" (or other error messages) in the textbox with the "unexpected error"?
BR

**Comment by azahajkiewicz** [comment]
It's a general implementation of the HTTP protocol: https://httpstatuses.com/
Journeys handles some specific errors, but for a general one (not Journeys specific) there's only status code returned with: "unexpected error" message. Probably we could add a nicer text/reason.

**Comment by asattndr** [comment]
you are right :) thank you very much
