### ISSUE TITLE
[BUG] s.detail[Object.keys[...].join is not a function

### ISSUE THREAD

**Issue by kamalao2004** [f5devcentral/f5-journeys#38]
After upgrade the image to version 3.2 , when create session I get the message attached

**To Reproduce**
1. upgrade from 3.0 to 3.2
2. follow up upgrade commands
3. See error

**Expected behavior**

**Screenshots**
![Journey_error](https://user-images.githubusercontent.com/82259890/157444489-2e585053-5ded-498d-aecf-c744972d734d.GIF)

**Context**
- Please specify, app version:

- And Platform version of the system you want to migrate.

**Comment by kamalao2004** [comment]
[journey_log.txt](https://github.com/f5devcentral/f5-journeys/files/8214776/journey_log.txt)
Journey log attached

**Comment by jszczepanskif5** [comment]
Hey! My guess looking at the log is that you need to update your `.env` file, prepared in the initial app setup (step 2 of install). Looks like between 3.0.0 and 3.2.0 some entries were added in the `sample.env` file, and I did not take into consideration the potential need to update it as well when writing the upgrade instructions.

That said, I do agree that UI error messages should be much cleaner in regards to any set-up issues and I will open an internal task to fix that.

**Comment by kamalao2004** [comment]
Hi Support Thank you . it work fine now

 

    On Wednesday, March 9, 2022, 06:54:36 PM GMT+3, jszczepanskif5 ***@***.***> wrote:  
 
 


Hey! My guess looking at the log is that you need to update your .env file, prepared in the initial app setup (step 2 of install). Looks like between 3.0.0 and 3.2.0 some entries were added in the sample.env file, and I did not take into consideration the potential need to update it as well when writing the upgrade instructions.

That said, I do agree that UI error messages should be much cleaner in regards to any set-up issues and I will open an internal task to fix that.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
