### ISSUE TITLE
[BUG] Impossible to load heavy UCS file

### ISSUE THREAD

**Issue by thejuicy** [f5devcentral/f5-journeys#40]
Hello,
When we try to upload and process a heavy ucs file, journeys hangs and finally crashes with an error.
We've tried with a smaller file, it works nice.

Here is the screencaps :
![image](https://user-images.githubusercontent.com/54108361/158843423-1018ae7d-fc7a-4e99-a0d7-478a78d77ea1.png)

**To Reproduce**
Upload a heavy UCS file (1GB and more)

**Context**
- Please specify, app version: 3.2.4

- And Platform version of the system you want to migrate.
12.1.1 to 15.1.4

**Comment by rjouhann** [comment]
Hello,

Would it be possible for you to create an SR ticket uploading the problematic UCS file for us to investigate? https://www.f5.com/services/support

Thanks & Regards,
Roman

**Comment by thejuicy** [comment]
Hello Roman, thanks for your quick answer. As the choice is owned by the customer, I'm waiting for his feedback in order to do or not the upload. Thanks !

**Comment by thejuicy** [comment]
Hello, after investigation, it was not the weight of the file. But the issue is still there, the file will be uploaded to the F5 support platform, as desired. Many thanks, I suppose you can close the issue here

**Comment by rjouhann** [comment]
@thejuicy  could you communicate the SR number? I looked in our database but could not find it. Thanks!

**Comment by thejuicy** [comment]
Here it is : SR# 1-8146055950

**Comment by rjouhann** [comment]
Merci! We will look into it and get back to you here.

**Comment by KubaTaba1uga** [comment]
The bug was fixed in version 3.3.2.  
I am closing the ticket. If you have any other issues/feedback, please open a new ticket.
Thank you!
