### ISSUE TITLE
[BUG] Full migration fails with message about DHCP being used for Management-ip but it is not for the source or destination

### ISSUE THREAD

**Issue by jamiekowalczik** [f5devcentral/f5-journeys#41]
**Describe the bug**
Full migration fails with message about DHCP being used for Management-ip but it is not for the source or destination

**To Reproduce**
In a full migration from a physical BIG-IP 5000 running v12.1.5.3 to a VE running the same version I receive the following error.

01071635:3: /Common/management-ip: Conflicting configuration. Management-ip can't be created manually while DHCP is enabled. Within tmsh run 'modify sys global-settings mgmt-dhcp disabled' before manually changing the management-ip.
Unexpected Error: Validating configuration process failed.

I've confirmed that both the source and destination have mgmt-dhcp disabled:
sys global-settings {
    mgmt-dhcp disabled
}

**Expected behavior**
Lack of error 01071635:3

**Screenshots**
tmsh list /sys global-settings mgmt-dhcp on both the source and destination have the following output:
sys global-settings {
    mgmt-dhcp disabled
}

**Context**
- Please specify, app version:
Journeys Release 3.3.0

- And Platform version of the system you want to migrate.
BIG-IP 5000 running v12.1.5.3 attempting to migrate to BIG-IP VE running v12.1.5.3

**Comment by jamiekowalczik** [comment]
Absolutely, although I am creating a new UCS file from that device excluding the private keys.  If that will be problematic, let's discuss through the SR.  1-8133879314

**Comment by rjouhann** [comment]
Yes, UCS without the private keys would be perfect! thanks!

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-6138.

**Comment by KubaTaba1uga** [comment]
Hello @jamiekowalczik,
 
Sadly attempts to reproduce Your issue using default 
VE v12.1.5.3 settings has failed. 
Please look at those articles, maybe they'll help You:
https://cdn.f5.com/product/bugtracker/ID653928.html
https://support.f5.com/csp/article/K76240727

During issue recreation, I met another problem which
was related to LACP:
 

> &emsp; /usr/bin/tmsh -n -g load sys config partitions all platform-migrate" - failed. 
> &emsp; – 01070687:3: Link Aggregation Control Protocol (LACP) is not supported on 
> &emsp; this platform. Unexpected Error: Loading configuration process failed.

 
To go over It You need to either comment out the whole LACP 
interface section or comment out the LACP entries in the 
interface in Your ucs file. Example:

> &emsp; Before:
> &emsp; &emsp; net trunk lacp-trunk-uplink {
> &emsp; &emsp;&emsp; interfaces {
> &emsp; &emsp;&emsp; &emsp; \<interface number\> 
> &emsp; &emsp;&emsp; &emsp; \<interface number\> 
> &emsp; &emsp;&emsp; } 
> &emsp; &emsp;&emsp; lacp enabled 
> &emsp; &emsp;&emsp; lacp-timeout short 
> &emsp; &emsp;&emsp; stp disabled 
> &emsp; &emsp; }

> &emsp; After:
> &emsp; &emsp; #net trunk lacp-trunk-uplink {
> &emsp; &emsp; &emsp; #    interfaces {
> &emsp; &emsp; &emsp; &emsp; #        \<interface number\>
> &emsp; &emsp; &emsp; &emsp; #        \<interface number\>
> &emsp; &emsp; &emsp; #    }
> &emsp; &emsp; &emsp; #    lacp enabled
> &emsp; &emsp; &emsp; #    lacp-timeout short
> &emsp; &emsp; &emsp; #    stp disabled
> &emsp; &emsp; #}

 
To help Us resolve Your problem please, upload destination
VE's ucs, into your SR.

**Comment by KubaTaba1uga** [comment]
Did the migration succeed, after walk-around described by You?

**Comment by azahajkiewicz** [comment]
I am closing the ticket. If you have any other issues/feedback, please open a new ticket.
Thank you!
