### ISSUE TITLE
error when running docker-compose

### ISSUE THREAD

**Issue by boreal321** [f5devcentral/f5-journeys#42]
**Describe the bug**
I get the following error when i run `docker-compose pull`

`ERROR: Named volume "working/db:/var/lib/postgresql/data:rw" is used in service "postgres" but no declaration was found in the volumes section.`

**To Reproduce**
1. run `docker-compose pull`

**Expected behavior**
Images should get downloaded but they don't.

**Screenshots**
n/a

**Context**
- Please specify, app version: `3.3.0`

- And Platform version of the system you want to migrate: n/a

- The platform running docker: macos catalina `v 10.15.7`

**Comment by jszczepanskif5** [comment]
Hey! The `WORKING_DIRECTORY` env variable, which I believe you have set to `working`, needs to be an absolute path (e.g. `/home/user/working` instead of `working`. Thanks for pointing this out, I'll note this in the README.

**Comment by rjouhann** [comment]
@boreal321 were you able to get the Journeys app running?

**Comment by boreal321** [comment]
Yes. Your suggestion fixed my issue. Thanks!

**Comment by rjouhann** [comment]
Awesome, thanks for the update, the team already added a [note](https://github.com/f5devcentral/f5-journeys#preparing-the-environment) :)

_If you are using a different working directory than the one shown in the point above, WORKING_DIRECTORY variable has to be updated in the .env file. Its value should be an absolute path pointing to your custom directory._
