### ISSUE TITLE
[BUG]f5-journeys_postgres_1 keep restarting PORT:0 Windows 10

### ISSUE THREAD

**Issue by nge66a** [f5devcentral/f5-journeys#48]
**Describe the bug**

**To Reproduce**
1. On Windows10 WSL, install docker, docker-compose, f5-journeys-app, start docker-compose
2. Enter command 'docker-compose up -d'
3. All 3 processes are red. Manually start f5-journeys_redis_1 and f5-journeys_acc-api_1. Works. But f5-journeys_postgre_1 fails.
https://localhost:8443/ also failed to connect.

postgres_1  | Error: Database is uninitialized and superuser password is not specified.
postgres_1  |        You must specify POSTGRES_PASSWORD to a non-empty value for the
postgres_1  |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
postgres_1  | 
postgres_1  |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
postgres_1  |        connections without a password. This is *not* recommended.
postgres_1  | 
postgres_1  |        See PostgreSQL documentation about "trust":
postgres_1  |        https://www.postgresql.org/docs/current/auth-trust.html

**Expected behavior**
https://localhost:8443/ should open the Journeys GUI.

**Screenshots**

![image](https://user-images.githubusercontent.com/59593841/163274359-9e8da807-3733-4843-93b8-d2ac09abf450.png)

**Context**
- Please specify, app version:
NA
- And Platform version of the system you want to migrate.
NA

**Comment by zahajkiewicz** [comment]
Have you followed the env preparation procedure, especially (2) copying env file?
`cp sample.env .env`

**Comment by rjouhann** [comment]
@zahajkiewicz would the variable `WORKING_DIRECTORY=/tmp/journeys` be different for Windows? 

Like `WORKING_DIRECTORY="C:\Users\bob\journeys"` assuming user created a folder in "C:\Users\bob".

**Comment by zahajkiewicz** [comment]
Yes, it should look different. But it seems .env file, where postgres vars are declared:

```
DB_NAME=postgres
DB_USER=postgres
DB_PASS=postgres
DB_HOST=postgres
```
was not copied (it resides in the current dir - repository, not WORKING_DIRECTORY).

**Comment by nge66a** [comment]
I have good news to report. 
I was able to start Journeys-app after changing the WORKING_DIRECTORY variable.
 
On PC, find current working directory.
nge@FLD-L-00060668:/mnt/c/Users/ge/f5-journeys$ pwd
/mnt/c/Users/ge/f5-journeys

Update .env with above working directory
nge@FLD-L-00060668:/mnt/c/Users/ge/journeys$ vi .env
WORKING_DIRECTORY=/mnt/c/Users/ge/journeys

Restart docker-compose from PowerShell. Successful.
PS C:\Users\ge\f5-journeys> pwd

Path
----
C:\Users\ge\f5-journeys


PS C:\Users\ge\f5-journeys> docker-compose up -d
Recreating f5-journeys_postgres_1 ...
Recreating f5-journeys_postgres_1 ... done
Recreating f5-journeys_acc-api_1  ... done
Creating f5-journeys_journeys_1   ... done
Creating f5-journeys_celery-worker_1 ... done

At this point, the GUI is accessable from https://localhost:8443/

I also tried to start docker-compose from WSL but failed.
The command 'docker-compose' could not be found in this WSL 1 distro.
We recommend to convert this distro to WSL 2 and activate
the WSL integration in Docker Desktop settings.

**Comment by nge66a** [comment]
![image](https://user-images.githubusercontent.com/59593841/163603651-e2e3a17c-c7b2-4ea7-8978-42b4a33d8074.png)

**Comment by rjouhann** [comment]
Issue resolved.
