### ISSUE TITLE
f5-journeys-journeys-1 image fails ~10 seconds after starting

### ISSUE THREAD

**Issue by iluvpcs** [f5devcentral/f5-journeys#49]
**Describe the bug**
When following the setup instructions, 4 of the 5 containers start without issue.  This one runs for <10 seconds and exits.
OS Mac Monterey with M1 chipset w/  latest Docker 4.7 (shouldn't matter).

Full Log from instance running (except for key).

Database information:
engine: django.db.backends.postgresql_psycopg2 
host: postgres 
port: 5432 
name: postgres 
user: postgres 
Waiting for database...
Database: available!
Migrations for 'backend':
/code/journeys/backend/migrations/0001_initial.py
    - Create model Application
    - Create model Commit
    - Create model Conflict
    - Create model Deployment
    - Create model DeviceDb
    - Create model Session
    - Create model LoadValidation
    - Create model VirtualServer
    - Create model Tenant
    - Create model ScopedModification
    - Create model PerappChange
    - Create model Mitigation
    - Create model File
    - Create model DeploymentResult
    - Add field session to deployment
    - Add field session to conflict
    - Add field session to commit
    - Create model Change
    - Add field session to application
    - Add field tenant to application
    - Create constraint unique_virtual_name_per_session on model virtualserver
    - Create constraint unique_tenant_per_session on model tenant
    - Create constraint unique_conflict_per_session on model conflict
    - Create constraint unique_app_name_per_session on model application
Starting JOURNEYS...
Certificate:
Generating a RSA private key
..................................................++++
.......................................................................................................................++++
writing new private key to '/etc/ssl/server_certs/server.key'
-----
*** Starting uWSGI 2.0.19.1 (64bit) on [Thu Apr 14 15:03:33 2022] ***
compiled with version: 10.2.1 20201203 on 30 March 2022 16:37:12
os: Linux-5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022
nodename: ada715354aa6
machine: x86_64
clock source: unix
detected number of CPU cores: 5
current working directory: /migrate
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
async cores set to 40 - fd table size: 1048576
lock engine: pthread robust mutexes
unable to set PTHREAD_PRIO_INHERIT

**Comment by iluvpcs** [comment]
CLI history steps:

git clone https://github.com/f5devcentral/f5-journeys.git\ncd f5-journeys
mkdir /tmp/journeys
cp sample.env .env
docker-compose pull
docker-compose up -d

**Comment by zahajkiewicz** [comment]
We are aware of this issue, tracking it internally with MBIPMP-7721.

**Comment by init4** [comment]
I'm hitting this bug too - any idea when a fix will be available?

**Comment by rjouhann** [comment]
Hello @init4, we are still working on fixing this bug, soon but no ETA yet. Thanks!

**Comment by rjouhann** [comment]
Fixed in [3.3.3](https://github.com/f5devcentral/f5-journeys/releases/tag/v3.3.3)
