### ISSUE TITLE
[FEAT] Check for modified default profiles and create new profile with existing settings

### ISSUE THREAD

**Issue by cbarthlomef5** [f5devcentral/f5-journeys#51]
**Is your feature request related to a problem? Please describe.**
Some customers have modified the default BigIP profiles in older version of BigIP. This can potentially cause issues during migration to a newer version of BigIP that does not support modification of default profiles. This can also result in a loss of configuration if there is no documentation on which settings are modified in the default profile.

**Describe the solution you'd like**
Check if default profile has been modified. If it has, create a new profile with configuration based on the modified default profile.

**Additional context**
Creating a new profile with previously modified default profile will retain settings which were in use.

**Comment by f5-purc** [comment]
Not planned to support.
