### ISSUE TITLE
[FEAT] Re-create DSC cluster after migration

### ISSUE THREAD

**Issue by justinbeckham** [f5devcentral/f5-journeys#53]
**Is your feature request related to a problem? Please describe.**
DSC groups can be difficult to properly configure and setup, so it would be good if the Journey's tool can re-create it on a new device rather than just converting an HA pair to standalone, which then requires the user to manually create it. 

**Describe the solution you'd like**
Have the tool output a UCS that contains the DSC configuration, optionally with the old management IP or give the user a facility to input what the new one will be. 

**Describe alternatives you've considered**
Alternatively have the tool recreate the DSC setup after the migration. 

**Additional context**
This is for a scenario where a customer wants to stand up a new pair of devices with the complete configuration from an older pair, but not have to join the devices into a single cluster (as this can sometimes lead to errors and unexpected downtime).

**Comment by f5-purc** [comment]
Not planned.
