### ISSUE TITLE
[FEAT] Please include the solution of TCL error: ERR_NOT_SUPPORTED after upgrade to version 14.1.0 or later

### ISSUE THREAD

**Issue by mi-garcia** [f5devcentral/f5-journeys#54]
It would be a great inclusion if you automate the iRule issues when you are upgrading up to 14.1.0 or later and the iRules show the TCL error: ERR_NOT_SUPPORTED.

https://support.f5.com/csp/article/K23237429

**Comment by rjouhann** [comment]
Filed internal Jira SOLUTIONS-5114.

**Comment by f5-purc** [comment]
We'll be supporting iRules migration in another solution.
