### ISSUE TITLE
[BUG] 404 ERROR - page can be found on docker hub repository

### ISSUE THREAD

**Issue by endymion93** [f5devcentral/f5-journeys#55]
**Describe the bug**
A 404 page error when : 5/ Examine if image listed in docker-compose journeys/celery-worker has exactly the same digest that can be found on docker hub repository with the same tag

https://hub.docker.com/r/f5devcentral/f5-bigip-journeys-app/tags?page=1&ordering=last_updated

**To Reproduce**
1. Go to  https://hub.docker.com/r/f5devcentral/f5-bigip-journeys-app/tags?page=1&ordering=last_updated
2. See error

**Expected behavior**

**Screenshots**

**Context**
- Please specify, app version:
Last

![docker_journey_404](https://user-images.githubusercontent.com/65768946/165794710-ad63d4f9-69b0-42d5-be4c-99ddc508b027.PNG)

- And Platform version of the system you want to migrate.

**Comment by rjouhann** [comment]
Hello @endymion93 ,

It is very strange, when I go on the same [link](https://hub.docker.com/r/f5devcentral/f5-bigip-journeys-app/tags?page=1&ordering=last_updated), I am not getting the same 404 error.

I am wondering if this is a problem on the docker side of things. I am in Seattle, which part of the world are you?

<img width="1518" alt="Screen Shot 2022-04-28 at 9 03 54 AM" src="https://user-images.githubusercontent.com/25542366/165796176-71591d16-7872-4029-953f-670145dbca38.png">

Thanks!

**Comment by zahajkiewicz** [comment]
The link also works for me.

**Comment by endymion93** [comment]
hy
Oops, sorry for the inconvenience, it seems that the problem came from our DNS. 
it's ok from france, today.
thank
