### ISSUE TITLE
[FEAT] Migrate shared configurations only

### ISSUE THREAD

**Issue by dwigley** [f5devcentral/f5-journeys#60]
**Is your feature request related to a problem? Please describe.**
migrate shared (Module) configurations only

**Describe the solution you'd like**
Currently this helps with 'like for like' migrations. However often times the base system is already set up and I just need Virtual Servers, Awaf Policies, AFM Policies, APM configurations ect ect to be migrated. Often times I am moving from one system to another and the Hostname, Device Cert, Networking (VLANs and Self IPs) are already configured because they are changing from the Legacy system to the newly deployed system.

**Describe alternatives you've considered**
Currently I keep dropping back to using SCF files and the associated .tar file to do migrations because I can pull all the Clustering, Networking, Hostname ect out of the file and just merge in what I want. This has limitations as the full ASM policies are not there.

**Additional context**
I would like some where for it to be an option asking what data you want to bring over from the Legacy system and uncheck or easily remove system configurations like Networking, Clustering but ensuring that full configurations for each module come over.

**Comment by rjouhann** [comment]
Hello @dwigley 
Thanks for your feedback. Have you had a chance to look into the [per-app migration](https://github.com/f5devcentral/f5-journeys#journey-application-service-migration) flow? I know this only supports LTM+SSL cert&keys but we would like to add ASM policy eventually too.
Thanks

**Comment by dwigley** [comment]
Good afternoon,
I have looked at that but it seems to want to do everything via AS3 and create a JSON file. I usually don't have a client that is able or willing to do things the new way they just want good ol TMOS (tmsh load sys config...)

**Comment by rjouhann** [comment]
Hello @dwigley 
You could technically use Journeys Per-App (using AS3) to do the migration, but then nobody forces you to use AS3 to manage the migrated config :) You can also use the good old TMOS. It's not what I recommend but this would work fine too!
Best,
