### ISSUE TITLE
[FEAT] Ability to output multiple AS3 declarations per tenant

### ISSUE THREAD

**Issue by mwardbopp** [f5devcentral/f5-journeys#62]
I have a customer with a large config 400+ applications and they would like to split this into a declaration per tenant so that they can migrate per app/groups of apps.

It would be great to have the ability to be able to output multiple separate AS3 declarations instead of a single declaration when selecting the entire configuration. If this could be achieved with the API that would also be suitable.

**Comment by mwardbopp** [comment]
Thanks Romain!

**Comment by f5-purc** [comment]
Workaround provided, not a feature planned for this app. Will be supported elsewhere.
