### ISSUE TITLE
[BUG] Large UCS config failed message, but config is loaded

### ISSUE THREAD

**Issue by mwardbopp** [f5devcentral/f5-journeys#63]
Follow-on from https://github.com/f5devcentral/f5-journeys/issues/61

When the UCS is loaded initially I get a config failed to load message, after 10+minutes. But if I exit/go back into "session" the config is loaded and the AS3 declarations are able to generate.

**Comment by zahajkiewicz** [comment]
@mwardbopp : before uploading a UCS, could you open a `Developer Tools -> Network section` to see what kind of error is returned in a response?

Chrome: view -> Developer -> Developer Tools
Mozilla: Tools -> Browser Tools -> Web Developer Tools

**Comment by mwardbopp** [comment]
Configuration loading failed is what shows up. I have the har file and UCS can you email me internally and I'll share?
![Screenshot 2022-05-30 at 11 01 26](https://user-images.githubusercontent.com/29975090/170969336-16dc99a4-c4ec-479c-bc63-111a268f6574.png)

**Comment by zahajkiewicz** [comment]
@mwardbopp: `Configuration loading failed` error comes from GUI, we need to check what is the real problem by seeing backend response.

Could you provide journeys.log which is stored in your WORKING_DIRECTORY?

**Comment by mwardbopp** [comment]
DEBUG 2022-05-30 09:50:06,163 schema CREATE TABLE "django_migrations" ("id" serial NOT NULL PRIMARY KEY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL); (params None)
DEBUG 2022-05-30 09:50:06,777 schema CREATE TABLE "django_content_type" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL); (params None)
DEBUG 2022-05-30 09:50:06,906 schema ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model"); (params ())
DEBUG 2022-05-30 09:50:06,981 schema ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL; (params [])
DEBUG 2022-05-30 09:50:06,984 schema ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE; (params ())
DEBUG 2022-05-30 09:50:06,990 schema CREATE TABLE "auth_permission" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL); (params None)
DEBUG 2022-05-30 09:50:07,060 schema CREATE TABLE "auth_group" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(80) NOT NULL UNIQUE); (params None)
DEBUG 2022-05-30 09:50:07,228 schema CREATE TABLE "auth_group_permissions" ("id" serial NOT NULL PRIMARY KEY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:07,382 schema CREATE TABLE "auth_user" ("id" serial NOT NULL PRIMARY KEY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL); (params None)
DEBUG 2022-05-30 09:50:07,938 schema CREATE TABLE "auth_user_groups" ("id" serial NOT NULL PRIMARY KEY, "user_id" integer NOT NULL, "group_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:07,982 schema CREATE TABLE "auth_user_user_permissions" ("id" serial NOT NULL PRIMARY KEY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:07,993 schema ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename"); (params ())
DEBUG 2022-05-30 09:50:08,018 schema ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,020 schema CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id"); (params ())
DEBUG 2022-05-30 09:50:08,042 schema CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops); (params ())
DEBUG 2022-05-30 09:50:08,068 schema ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id"); (params ())
DEBUG 2022-05-30 09:50:08,074 schema ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,075 schema ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,076 schema CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id"); (params ())
DEBUG 2022-05-30 09:50:08,100 schema CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id"); (params ())
DEBUG 2022-05-30 09:50:08,104 schema CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops); (params ())
DEBUG 2022-05-30 09:50:08,125 schema ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id"); (params ())
DEBUG 2022-05-30 09:50:08,178 schema ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,180 schema ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,181 schema CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id"); (params ())
DEBUG 2022-05-30 09:50:08,225 schema CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id"); (params ())
DEBUG 2022-05-30 09:50:08,229 schema ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id"); (params ())
DEBUG 2022-05-30 09:50:08,265 schema ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,267 schema ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:08,268 schema CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id"); (params ())
DEBUG 2022-05-30 09:50:08,271 schema CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id"); (params ())
DEBUG 2022-05-30 09:50:08,374 schema ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255); (params [])
DEBUG 2022-05-30 09:50:08,384 schema ALTER TABLE "auth_user" ALTER COLUMN "email" TYPE varchar(254); (params [])
DEBUG 2022-05-30 09:50:08,402 schema ALTER TABLE "auth_user" ALTER COLUMN "last_login" DROP NOT NULL; (params [])
DEBUG 2022-05-30 09:50:08,444 schema ALTER TABLE "auth_user" ALTER COLUMN "username" TYPE varchar(150); (params [])
DEBUG 2022-05-30 09:50:09,022 schema ALTER TABLE "auth_user" ALTER COLUMN "last_name" TYPE varchar(150); (params [])
DEBUG 2022-05-30 09:50:09,032 schema ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150); (params [])
DEBUG 2022-05-30 09:50:09,050 schema ALTER TABLE "auth_user" ALTER COLUMN "first_name" TYPE varchar(150); (params [])
DEBUG 2022-05-30 09:50:09,055 schema CREATE TABLE "backend_application" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(1024) NOT NULL, "description" varchar(1000) NULL, "last_modified" timestamp with time zone NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,064 schema CREATE TABLE "backend_commit" ("id" serial NOT NULL PRIMARY KEY, "sha" varchar(64) NULL); (params None)
DEBUG 2022-05-30 09:50:09,070 schema CREATE TABLE "backend_conflict" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(32) NOT NULL, "summary" text NOT NULL, "affected_objects" jsonb NOT NULL, "resolved" boolean NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,080 schema CREATE TABLE "backend_deployment" ("id" serial NOT NULL PRIMARY KEY, "source" varchar(128) NULL, "destination" varchar(128) NULL, "validators" jsonb NULL, "status" varchar(32) NOT NULL, "backup_name" varchar(256) NULL, "logs_pointers" jsonb NULL, "details" jsonb NULL, "output_as3_path" varchar(500) NULL); (params None)
DEBUG 2022-05-30 09:50:09,092 schema CREATE TABLE "backend_devicedb" ("id" serial NOT NULL PRIMARY KEY, "host" varchar(32) NULL, "type" varchar(32) NOT NULL, "platform" varchar(20) NULL, "version" varchar(32) NULL); (params None)
DEBUG 2022-05-30 09:50:09,099 schema CREATE TABLE "backend_session" ("id" serial NOT NULL PRIMARY KEY, "journey_type" integer NOT NULL, "last_update_time" timestamp with time zone NOT NULL, "name" varchar(255) NOT NULL, "description" varchar(1000) NOT NULL, "current_conflict" varchar(128) NULL, "warnings" jsonb NOT NULL, "instructions" text NULL, "initial_conflicts" jsonb NOT NULL, "working_directory" varchar(500) NOT NULL, "input_ucs_name" varchar(128) NULL, "files_metadata" jsonb NOT NULL, "input_as3_name" varchar(128) NULL, "output_ucs_name" varchar(256) NULL, "output_as3_path" varchar(500) NULL, "decoded_as3_irules" jsonb NOT NULL, "hostname" varchar(128) NULL, "last_page" text NOT NULL, "per_app_overlapping_objects_config" jsonb NOT NULL, "config_files" jsonb NOT NULL, "locked" boolean NOT NULL, "destination_id" integer NULL UNIQUE, "source_id" integer NULL UNIQUE); (params None)
DEBUG 2022-05-30 09:50:09,119 schema CREATE TABLE "backend_loadvalidation" ("session_id" integer NOT NULL PRIMARY KEY, "ucs_to_verify_name" varchar(35) NULL, "backup_name" varchar(35) NULL, "log" text NULL, "result" boolean NULL, "as3_to_verify_name" varchar(35) NULL); (params None)
DEBUG 2022-05-30 09:50:09,134 schema CREATE TABLE "backend_virtualserver" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(1024) NOT NULL, "description" varchar(1000) NOT NULL, "folder" varchar(2048) NOT NULL, "last_modified" timestamp with time zone NOT NULL, "partition_object_ids" jsonb NOT NULL, "common_object_ids" jsonb NOT NULL, "deployable_objects" jsonb NOT NULL, "as3_status" integer NULL, "output" jsonb NULL, "unsupported" jsonb NULL, "metadata" jsonb NULL, "address" varchar(2048) NULL, "pool" varchar(200) NULL, "application_id" integer NOT NULL, "session_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,150 schema CREATE TABLE "backend_tenant" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(1024) NOT NULL, "description" varchar(1000) NULL, "staged" boolean NOT NULL, "session_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,167 schema CREATE TABLE "backend_scopedmodification" ("id" serial NOT NULL PRIMARY KEY, "object_ids" jsonb NOT NULL, "required_objects_ids" jsonb NOT NULL, "file_path" varchar(1024) NOT NULL, "base_file" varchar(255) NOT NULL, "session_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,184 schema CREATE TABLE "backend_perappchange" ("id" serial NOT NULL PRIMARY KEY, "operation" integer NOT NULL, "changed_id" integer NOT NULL, "serialized" text NULL, "changed_type_id" integer NOT NULL, "commit_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,197 schema CREATE TABLE "backend_mitigation" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(512) NOT NULL, "conflict_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,210 schema CREATE TABLE "backend_file" ("id" serial NOT NULL PRIMARY KEY, "path" varchar(512) NOT NULL, "mitigation_id" integer NULL); (params None)
DEBUG 2022-05-30 09:50:09,220 schema CREATE TABLE "backend_deploymentresult" ("id" serial NOT NULL PRIMARY KEY, "time" timestamp with time zone NOT NULL, "message" text NOT NULL, "level" integer NOT NULL, "deployment_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,241 schema ALTER TABLE "backend_deployment" ADD COLUMN "session_id" integer NOT NULL CONSTRAINT "backend_deployment_session_id_25e43dfd_fk_backend_session_id" REFERENCES "backend_session"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "backend_deployment_session_id_25e43dfd_fk_backend_session_id" IMMEDIATE; (params [])
DEBUG 2022-05-30 09:50:09,251 schema ALTER TABLE "backend_conflict" ADD COLUMN "session_id" integer NOT NULL CONSTRAINT "backend_conflict_session_id_3f9cad47_fk_backend_session_id" REFERENCES "backend_session"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "backend_conflict_session_id_3f9cad47_fk_backend_session_id" IMMEDIATE; (params [])
DEBUG 2022-05-30 09:50:09,267 schema ALTER TABLE "backend_commit" ADD COLUMN "session_id" integer NOT NULL CONSTRAINT "backend_commit_session_id_da98982a_fk_backend_session_id" REFERENCES "backend_session"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "backend_commit_session_id_da98982a_fk_backend_session_id" IMMEDIATE; (params [])
DEBUG 2022-05-30 09:50:09,284 schema CREATE TABLE "backend_change" ("id" serial NOT NULL PRIMARY KEY, "message" varchar(512) NOT NULL, "commit" varchar(64) NOT NULL, "diffs" jsonb NOT NULL, "resolves" jsonb NOT NULL, "session_id" integer NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,313 schema ALTER TABLE "backend_application" ADD COLUMN "session_id" integer NOT NULL CONSTRAINT "backend_application_session_id_3baa39d2_fk_backend_session_id" REFERENCES "backend_session"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "backend_application_session_id_3baa39d2_fk_backend_session_id" IMMEDIATE; (params [])
DEBUG 2022-05-30 09:50:09,330 schema ALTER TABLE "backend_application" ADD COLUMN "tenant_id" integer NOT NULL CONSTRAINT "backend_application_tenant_id_1827c69f_fk_backend_tenant_id" REFERENCES "backend_tenant"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "backend_application_tenant_id_1827c69f_fk_backend_tenant_id" IMMEDIATE; (params [])
DEBUG 2022-05-30 09:50:09,341 schema ALTER TABLE "backend_virtualserver" ADD CONSTRAINT "unique_virtual_name_per_session" UNIQUE ("name", "session_id"); (params ())
DEBUG 2022-05-30 09:50:09,356 schema ALTER TABLE "backend_tenant" ADD CONSTRAINT "unique_tenant_per_session" UNIQUE ("name", "session_id"); (params ())
DEBUG 2022-05-30 09:50:09,369 schema ALTER TABLE "backend_conflict" ADD CONSTRAINT "unique_conflict_per_session" UNIQUE ("name", "session_id"); (params ())
DEBUG 2022-05-30 09:50:09,385 schema ALTER TABLE "backend_application" ADD CONSTRAINT "unique_app_name_per_session" UNIQUE ("name", "session_id"); (params ())
DEBUG 2022-05-30 09:50:09,394 schema ALTER TABLE "backend_session" ADD CONSTRAINT "backend_session_destination_id_a8e22b03_fk_backend_devicedb_id" FOREIGN KEY ("destination_id") REFERENCES "backend_devicedb" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,396 schema ALTER TABLE "backend_session" ADD CONSTRAINT "backend_session_source_id_fb84469c_fk_backend_devicedb_id" FOREIGN KEY ("source_id") REFERENCES "backend_devicedb" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,397 schema ALTER TABLE "backend_loadvalidation" ADD CONSTRAINT "backend_loadvalidati_session_id_704e3f1d_fk_backend_s" FOREIGN KEY ("session_id") REFERENCES "backend_session" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,398 schema ALTER TABLE "backend_virtualserver" ADD CONSTRAINT "backend_virtualserve_application_id_d764bcb0_fk_backend_a" FOREIGN KEY ("application_id") REFERENCES "backend_application" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,399 schema ALTER TABLE "backend_virtualserver" ADD CONSTRAINT "backend_virtualserver_session_id_b030f7a3_fk_backend_session_id" FOREIGN KEY ("session_id") REFERENCES "backend_session" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,400 schema CREATE INDEX "backend_virtualserver_application_id_d764bcb0" ON "backend_virtualserver" ("application_id"); (params ())
DEBUG 2022-05-30 09:50:09,407 schema CREATE INDEX "backend_virtualserver_session_id_b030f7a3" ON "backend_virtualserver" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,410 schema ALTER TABLE "backend_tenant" ADD CONSTRAINT "backend_tenant_session_id_d430e92d_fk_backend_session_id" FOREIGN KEY ("session_id") REFERENCES "backend_session" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,411 schema CREATE INDEX "backend_tenant_session_id_d430e92d" ON "backend_tenant" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,420 schema ALTER TABLE "backend_scopedmodification" ADD CONSTRAINT "backend_scopedmodifi_session_id_b4c6de12_fk_backend_s" FOREIGN KEY ("session_id") REFERENCES "backend_session" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,421 schema CREATE INDEX "backend_scopedmodification_session_id_b4c6de12" ON "backend_scopedmodification" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,435 schema ALTER TABLE "backend_perappchange" ADD CONSTRAINT "backend_perappchange_changed_type_id_80155512_fk_django_co" FOREIGN KEY ("changed_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,437 schema ALTER TABLE "backend_perappchange" ADD CONSTRAINT "backend_perappchange_commit_id_a1bf8e5a_fk_backend_commit_id" FOREIGN KEY ("commit_id") REFERENCES "backend_commit" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,438 schema CREATE INDEX "backend_perappchange_changed_type_id_80155512" ON "backend_perappchange" ("changed_type_id"); (params ())
DEBUG 2022-05-30 09:50:09,448 schema CREATE INDEX "backend_perappchange_commit_id_a1bf8e5a" ON "backend_perappchange" ("commit_id"); (params ())
DEBUG 2022-05-30 09:50:09,450 schema ALTER TABLE "backend_mitigation" ADD CONSTRAINT "backend_mitigation_conflict_id_13506d2e_fk_backend_conflict_id" FOREIGN KEY ("conflict_id") REFERENCES "backend_conflict" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,452 schema CREATE INDEX "backend_mitigation_conflict_id_13506d2e" ON "backend_mitigation" ("conflict_id"); (params ())
DEBUG 2022-05-30 09:50:09,456 schema ALTER TABLE "backend_file" ADD CONSTRAINT "backend_file_mitigation_id_f29891c9_fk_backend_mitigation_id" FOREIGN KEY ("mitigation_id") REFERENCES "backend_mitigation" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,457 schema CREATE INDEX "backend_file_mitigation_id_f29891c9" ON "backend_file" ("mitigation_id"); (params ())
DEBUG 2022-05-30 09:50:09,463 schema ALTER TABLE "backend_deploymentresult" ADD CONSTRAINT "backend_deploymentre_deployment_id_bc821ae7_fk_backend_d" FOREIGN KEY ("deployment_id") REFERENCES "backend_deployment" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,464 schema CREATE INDEX "backend_deploymentresult_deployment_id_bc821ae7" ON "backend_deploymentresult" ("deployment_id"); (params ())
DEBUG 2022-05-30 09:50:09,468 schema CREATE INDEX "backend_deployment_session_id_25e43dfd" ON "backend_deployment" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,472 schema CREATE INDEX "backend_conflict_session_id_3f9cad47" ON "backend_conflict" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,478 schema CREATE INDEX "backend_commit_session_id_da98982a" ON "backend_commit" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,481 schema ALTER TABLE "backend_change" ADD CONSTRAINT "backend_change_session_id_4e1284bc_fk_backend_session_id" FOREIGN KEY ("session_id") REFERENCES "backend_session" ("id") DEFERRABLE INITIALLY DEFERRED; (params ())
DEBUG 2022-05-30 09:50:09,483 schema CREATE INDEX "backend_change_session_id_4e1284bc" ON "backend_change" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,486 schema CREATE INDEX "backend_application_session_id_3baa39d2" ON "backend_application" ("session_id"); (params ())
DEBUG 2022-05-30 09:50:09,491 schema CREATE INDEX "backend_application_tenant_id_1827c69f" ON "backend_application" ("tenant_id"); (params ())
DEBUG 2022-05-30 09:50:09,498 schema CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL); (params None)
DEBUG 2022-05-30 09:50:09,513 schema CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops); (params ())
DEBUG 2022-05-30 09:50:09,516 schema CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date"); (params ())
WARNING 2022-05-30 09:57:21,385 log Bad Request: /sessions
ERROR 2022-05-30 09:57:31,882 handlers Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/code/journeys/backend/serializers.py", line 652, in to_representation
    result = super(SessionDetailsSerializer, self).to_representation(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "/code/journeys/backend/serializers.py", line 632, in get_tenants
    controller = MigrationController(session)
  File "/code/journeys/controller.py", line 89, in __init__
    self._ensure_is_master()
  File "/code/journeys/controller.py", line 149, in _ensure_is_master
    if self.repo.active_branch.name != "master":
AttributeError: 'MigrationController' object has no attribute 'repo'

ERROR 2022-05-30 09:57:31,884 log Internal Server Error: /sessions/1
WARNING 2022-05-30 10:11:24,524 log Conflict: /sessions/1/source

**Comment by wiksla** [comment]
@mwardbopp couldn't reproduce with other configs; sent you an internal email. Could you please provide the UCS which caused the problem?

**Comment by f5-purc** [comment]
Closed due to inactivity and unable to repro. Please open a new bug if the issue persists and provide requested information.
