### ISSUE TITLE
[BUG] Migration from BIG-IP HA to BIG-IP Standalone leave HA config in migrated config

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/f5-journeys#67]
**Describe the bug**
Opening this bug on behalf of Chris. Tried in his lab to migrate a BIG-IP from vCMP to VELOS, and we noticed the restored BIG-IP was containing artifacts of the secondary BIG-IP part of the cluster in the source. I believe the problem is the same as SOLUTIONS-6481.

Workaround is to execute the following command on the target device: 

`tmsh delete /cm trust-domain all`

**To Reproduce**
1. Get UCS from SR 1-6993580048\INCOMING\jun_10\lab02.ucs
2. Restore the UCS on a vCMP guest 14.1.4.6
3. Use Journeys 3.3.2 to migrate the config to a VELOS tenant 14.1.4.6 after resolving all the errors in the tool (including DeviceGroup)

**Context**
- Please specify, app version: 3.3.2
- And Platform version of the system you want to migrate: vCMP guest to VELOS tenant 14.1.4.6

**Comment by wiksla** [comment]
The bug was fixed in release 3.3.5
