### ISSUE TITLE
[BUG] Data Input Error:(/config/bigip_base.conf at line: 0) Invalid version:11.5.10

### ISSUE THREAD

**Issue by KitsapCharles** [f5devcentral/f5-journeys#73]
**Describe the bug**
Supported cli versions: 11.5.0 11.5.4 11.5.5 12.0.0 12.1.0 13.0.0 13.0.1 13.1.0 13.1.1 13.1.2 13.1.3 14.0.0 14.1.0 14.1.1 14.1.2 15.0.0 15.0.1 15.1.0 15.1.2 15.1.3

**To Reproduce**
1. Import UCS from v11.5.10 system
2. Target v15.1.3 system
3. Validation fails with Data Input Error

**Expected behavior**
Version 11.5.10 is the latest (and probably final) version in the 11.5.x branch and should be a valid source for conversion.

In addition, no 11.6.x version is listed as a valid source. 

**Context**
- Please specify, app version: 3.3.4

- And Platform version of the system you want to migrate. 
Source: Big-IP 1600
Target: Big-IP VM 15.1.3

**Comment by KitsapCharles** [comment]
So one can migrate from versions 11.5.0, 11.5.4, or 11.5.5, but not from any more recent 11.5.x version? Regardless of the target version? What would be involved in making this possible?

**Comment by f5-purc** [comment]
Is this still valid issue or has the workaround provided been used?

**Comment by azahajkiewicz** [comment]
@KitsapCharles You should open an SR ticket. It is a restriction coming from a BIG-IP software, not Journeys.
