### ISSUE TITLE
[BUG] Disable Passphrase check box doesn't appear to allow you to check it, but still disables passphrases. (UI Issue)

### ISSUE THREAD

**Issue by Jerry-Lees** [f5devcentral/f5-journeys#74]
**Describe the bug**
When preforming a offline full migration, when you attempt to disable the passphrase on a created UCS the check box to disable the passphrase doesn't appear to allow you to check it (the checkbox will not show "checked" no matter how many times you "spam" it)

However, after several migration tests I noticed it actually does disable the passphrase, assuming you only click it once and don't get frustrated and try to re-check it.

**To Reproduce**
1. Go to 'Full BIG-IP Migration'
2. Upload the UCS and "load configuration"
3. Click confirm when loaded
4. Click Next
5. Choose offline BIG-IP System
6. Select rSeries BIG-IP ver. 15.1.5 (I don't think this matters)
7. Click Next
8. Resolve conflicts and click next
9. Click Next again to get to teh Journey Summary Screen.
10. Click "Disable UCS passphrase"

**Expected behavior**
The checkbox checks and shows accurately if passphrases will or will not be disabled.

**Context**
- 3.3.4? (Version doesn't seem to be prominently displayed anywhere, but that's a feature request I suppose)

- Experienced with 7250v, 5250v, and VE Migrations. I suspect it will happen regardless of source platform

**Comment by azahajkiewicz** [comment]
@Jerry-Lees : what browser are you using? FYI, recommended ones are Chrome/Firefox.

**Comment by Jerry-Lees** [comment]
I am using FF 102.0.1.

**Comment by azahajkiewicz** [comment]
@Jerry-Lees: thank you for opening the issue, it is tracked internally: SOLUTIONS-7703

**Comment by wojtek0806** [comment]
I have verified this on 4.1.0 and it now works as intended, each time you come back to migration you need to generate a new UCS, and it allows you to set the Disable Passphrase checkbox and it correctly sends it to back end:
![Screenshot 2024-03-20 at 10 41 02](https://github.com/f5devcentral/f5-journeys/assets/18006037/42428467-f465-4c30-bd38-0f8fa77645a7)
![Screenshot 2024-03-20 at 10 44 40](https://github.com/f5devcentral/f5-journeys/assets/18006037/b8a82bcf-e879-4646-a90d-6790ba413093)
