### ISSUE TITLE
[FEAT] Do not flag a configuration as having WOM when WOM is only disabled

### ISSUE THREAD

**Issue by Jerry-Lees** [f5devcentral/f5-journeys#75]
**Is your feature request related to a problem? Please describe.**
When Journeys profivides a summary for a config without WOM profiles, but WOM is disabled in the configuration it flags the configuration as having WOM settings.

**Describe the solution you'd like**
Have Journeys ignore the config stanzas:

wom deduplication {
    disabled
}

And also any WOM options that are void of settings. for example:
wom endpoint-discovery { }

**Additional context**
I'm qualifying around (eventually) 200+ configurations for migration to possibly migrate to r-Series tenants, each has the stanzas mentioned above and must be manually reviewed. I've confirmed none (thus far, I only have 20-30) have WOM features enabled. This seems to be a false positive and may even be an upgrade artifact.

**Comment by Jerry-Lees** [comment]
FWIW, I verified that I can remove the stanzas mentioned above from a configuration before sending through journeys and it doesn't flag teh configuration as having WOM issues.

**Comment by siddharthsakthidharan** [comment]
Jerry, the goal when migrating to rSeries and VELOS platforms, is to "remove" any configuration objects that are not currently supported on platforms, even when disabled.

**Comment by Jerry-Lees** [comment]
My point was that there actually is no WOM/WAM configuration.

**Comment by azahajkiewicz** [comment]
@Jerry-Lees Journeys won't print warnings about WOM configuration if the only WOM object found is:
`wom endpoint-discovery { }`

which is the default one.
