### ISSUE TITLE
[BUG] Journeys flags configurations saying that they "Include HTTP3/QUIC objects or rules" when there are no profiles of this type created

### ISSUE THREAD

**Issue by Jerry-Lees** [f5devcentral/f5-journeys#76]
**Describe the bug**
Journeys seems to flag SOME configurations as having HTTP3 or QUIC configurations when no profiles of that type are in the configuration

**To Reproduce**
1. Go to 'Full BIG-IP Migration'
2. Upload the UCS and "load configuration" (UCS /config examples available via direct methods, reach out to me via my f5 email or teams)
3. Click confirm when loaded
4. Click Next
5. Note that the "Config includes HTTP3/QUIC object or rules." message is displayed.

Search bigip.conf for HTTP3 or QUIC, no profiles are found.

**Expected behavior**
No message should be displayed. Note that, not ALL configurations I have tested show this message so it's not nessisarily like the WOM issue I have opened previously.

**Context**
    3.3.4? (Version doesn't seem to be prominently displayed anywhere, but that's a feature request I suppose)

    Experienced with 7250v, 5250v, and VE Migrations. I suspect it will happen regardless of source platform

**Comment by azahajkiewicz** [comment]
Tracked internally with Jira SOLUTIONS-7135.

**Comment by wojtek0806** [comment]
The issue seem to be resolved with the latest 4.1.0 Recheck and raise a new bug if this occurs again
