### ISSUE TITLE
Offline BIG-IP system - only VELOS and rSeries availiable

### ISSUE THREAD

**Issue by dragonflymrpl** [f5devcentral/f5-journeys#77]
**Describe the bug**
I Am not sure if this is a bug or feature. After uploading archive I tried to use Offline BIG-IP system option but in popup I can see only VELOS and rSeries, no VE or iSeries or vCMP guest. So is that not possible to convert to those platforms or it's only possible if target is live device?

**To Reproduce**
2. Enter command '....'
3. See error

**Expected behavior**
Just would like to be able doing offline conversion with mentioned platforms as target.

**Screenshots**
![image](https://user-images.githubusercontent.com/110664326/183045485-6a29040d-365d-4e42-8dc7-dd970284c7a0.png)

**Context**
- v 3.3.4

**Comment by azahajkiewicz** [comment]
This is the expected behaviour. Currently Journeys supports offline mode only for VELOS and rSeries migrations.

**Comment by dragonflymrpl** [comment]
But Am I write it supports VE, vCMP and iSeries if target is set to actual device?

**Comment by azahajkiewicz** [comment]
Yes, if you provide IP address of any BIG-IP platform, it will be set as a destination.

**Comment by dragonflymrpl** [comment]
OK, so no plans for more choices in Offline mode?

**Comment by dragonflymrpl** [comment]
Last question. If I will select for example rSeries 15.1.6 will resulting configuration contain any objects/properties/parameters that will prevent loading such config on VE or vCMP Guest?

**Comment by azahajkiewicz** [comment]
Setting a destination to rSeries/VELOS means that any unsupported objects/properties/parameters on **those platforms** will be removed from the Source UCS.
This means Journeys might remove some configuration part which could be supported on another platforms.

**Comment by azahajkiewicz** [comment]
There is an improvement task to add different platforms to offline support, but it is not prioritised for now.

**Comment by azahajkiewicz** [comment]
> OK, so no plans for more choices in Offline mode?

There is an improvement task to add different platforms to offline support, but it is not prioritised for now.

**Comment by dragonflymrpl** [comment]
> Setting a destination to rSeries/VELOS means that any unsupported objects/properties/parameters on **those platforms** will be removed from the Source UCS. This means Journeys might remove some configuration part which could be supported on another platforms.

So it's only removing features not supported on VELOS/rSeries but is not adding anything specific to those platforms that will prohibit loading configuration on other platforms (after adding appropriate removed parts of the config) - Am I right?

**Comment by azahajkiewicz** [comment]
It depends on the mitigation chosen to resolve unsupported features. I can imagine sometimes it might change the configuration, so it might not be able to load on another system. So before selecting any mitigation within a destination platform, please make sure changes are not impacting other system, if you decide to select different offline destination system than the planned one (an option to see the changes done by Journeys is provided).

Just keep in mind that you won't be able to deploy the UCS automatically, since Journeys checks the destination platform selected in offline mode vs the target one. Either way, it is **not recommended** way to use Journeys.

**Comment by dragonflymrpl** [comment]
OK, thanks for info.
