### ISSUE TITLE
[FEAT] Batch process multiple UCS Achives for r-Series/Velos Migration

### ISSUE THREAD

**Issue by Jerry-Lees** [f5devcentral/f5-journeys#79]
As pre-iSeries devices become to the point of being out of software support and software development, many customers are going to have to upgrade to either iSeries or rSeries. Having the ability to classify en-mass which configurations will, at least in theory, are able to be upgraded to rSeries would be a BIG time saver. 

**Describe the solution you'd like**
In my case, UCS processing (no direct access to devices) would be beneficial but processing a list of live devices by providing IPs, usernames, and passwords would be beneficial to others.

Ideally, Journeys would take that input to generate a single report, maybe even a CSV, that said the device name (or UCS filename), if the device could be upgraded or not. If not, simply list the reasons why. For example:

BigIP01.company.local, Yes, N/A
BigIP03SSLO.company.local, No, Tunnels; HTTP3; CGNAT; etc

**Describe alternatives you've considered**
The alternative when you don't have access to the device from journeys is to upload one by one each UCS and go through the "full migration process" to get the output on the screen or in a more detailed report. If you did have access to the devices, you have to go through each device manually as well, just that you don't have to upload the UCS.

**Additional context**
- Customers who utilize "jumpboxes" for ssh access to devices must either jump through the jumpbox to manually get a UCS or one by one log into TMUI (if available) to gather UCS files to see if a device is a rSeries/VELOS candidate, then when migrating do the process again.
- Customers want to know going into a mass migration which devices will be problems.

**Comment by rjouhann** [comment]
Hey @Jerry-Lees, what about using [Journeys API](https://github.com/f5devcentral/f5-journeys#journeys-api) to automate multiple UCS Achives for r-Series/Velos Migration? There is an example on how easy is to consume Journeys API in the Journeys UDF blueprint.

**Comment by azahajkiewicz** [comment]
@rjouhann Thank you for pointing that out.
@Jerry-Lees closing the ticket, since it is up to a users to write their automation scripts.
