### ISSUE TITLE
[FEAT] Show Journeys version number in UI and on reports

### ISSUE THREAD

**Issue by f5jason** [f5devcentral/f5-journeys#81]
**Is your feature request related to a problem? Please describe.**
After running reports, I cannot determine which version of the tool was used. Newer tool versions might have changes in the recommendations, so would be good to know which version was used to generate the report.

**Describe the solution you'd like**
Display Journeys tool version number in the UI and on generated reports (PDFs).

**Comment by azahajkiewicz** [comment]
Tracked internally with: SOLUTIONS-7374

**Comment by f5-purc** [comment]
updated tracking id [MBIPMP-19506]

**Comment by wojtek0806** [comment]
changes in develop branch, will be available in next release
