### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kenny19850514** [f5devcentral/f5-journeys#86]
**Describe the bug**

**To Reproduce**
1. Go to 'cd /f5-journeys'
2. Enter command 'docker-compose pull --ignore-pull-failures'
3. See error

 ⠿ acc-api Error                                                                                                                    4.2s
Pulling acc-api: Error response from daemon: manifest for f5devcentral/f5-automation-config-converter:1.20.0 not found: manifest unknown: manifest unknown

**Expected behavior**
all should be abled to be pulled

**Screenshots**

**Context**
- Please specify, app version:
docker-compose v2.11.2

- And Platform version of the system you want to migrate.

**Comment by kenny19850514** [comment]
changed the docker-compose.yaml to

image: f5devcentral/f5-automation-config-converter:latest

**Comment by wiksla** [comment]
I have updated ACC version in the docker-compose file to 1.23.0
