### ISSUE TITLE
[BUG] Perapp configuration page is missing

### ISSUE THREAD

**Issue by balijanaresh** [f5devcentral/f5-journeys#90]
**Describe the bug**
During installation steps of 6 note of "Perapp Documentation" page is broken. Please try below link,

Perapp Documentation:
https://github.com/f5devcentral/f5-journeys/blob/main/PERAPP.md

**Comment by mnaumiuk** [comment]
perapp is for migrating LTM only - this info should be also added

**Comment by f5-purc** [comment]
tracked in MBIPMP-19504

**Comment by wojtek0806** [comment]
this has been consolidated and moved to main readme:
https://github.com/f5devcentral/f5-journeys?tab=readme-ov-file#journey-application-service-migration
