### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by smeisenzahl** [f5devcentral/f5-journeys#92]
**Is your feature request related to a problem? Please describe.**
 - We’re starting to see Journeys used for migrations with thousands of virtual servers. The way that objects are grouped into tennant1 and tennant2 does not tend to result in helpful naming conventions, and manually editing the JSON, even at an advanced find and replace level, isn’t particularly a practical solution.
 
**Describe the solution you'd like**
- Either allow input of a naming scheme or allow the tenant name to inherit the name of the virtual server.

**Describe alternatives you've considered**
- Manual or scripted modification of the JSON output.

**Additional context**
<img width="1067" alt="Screen Shot 2023-01-18 at 11 20 03 AM" src="https://user-images.githubusercontent.com/60409572/213233404-af0fa7cd-4e3d-419c-9520-3b80075427a0.png">
<img width="807" alt="Screen Shot 2023-01-18 at 11 20 19 AM" src="https://user-images.githubusercontent.com/60409572/213233424-6284551d-a879-4add-aae6-debe4814df35.png">
<img width="836" alt="Screen Shot 2023-01-18 at 11 20 33 AM" src="https://user-images.githubusercontent.com/60409572/213233430-cbe7fb0c-9496-4962-9121-0a6b7da009ae.png">

**Comment by f5-purc** [comment]
A user can update a tenant/application name in the GUI, it's not a bulk operation though.
Naming tenant/application after the vs name will be problematic, if there will be more than 1 vs in the tenant/app.

We are planning to update the app to use a new Application Service view that'll fix this problem permanently.

**Comment by smeisenzahl** [comment]
Thanks for the response, is there an estimated release date for this update?

**Comment by f5-purc** [comment]
No ETA as of now.
