### ISSUE TITLE
[BUG]Large live config fails to load with fatal: detected dubious ownership in repository at '/mnt/c/journeys/migrate...message

### ISSUE THREAD

**Issue by pun1sher** [f5devcentral/f5-journeys#93]
Journeys discovers device successful
Journeys attempts to load configuration...after 17 minutes it generates the following error message:

![image](https://user-images.githubusercontent.com/19553565/214758836-58c2f638-e224-4018-b4db-a8894bea6fba.png)

**Comment by pun1sher** [comment]
I added the exception noted above and reran the Journeys migration with the same error message as a result.

**Comment by f5-purc** [comment]
we'll need a ucs used here and logs

**Comment by wojtek0806** [comment]
Please retest with the latest 4.1.0 version (rebuild from scratch) and open a new issue using appropriate template providing sufficent data.
