### ISSUE TITLE
[BUG] Journeys says Uncompliant APP but Cant remove the problematic part in the editor

### ISSUE THREAD

**Issue by bernabecrena** [f5devcentral/f5-journeys#94]
**Describe the bug**
I uploaded a Big UCS and the migration assistant show all vs as Uncompliant APPs, but when I want to edit the configuration the system didnt save my changes. A extrange situation is they show net configurations, but didnt allow to eliminate them.

**To Reproduce**
1. Upload my UCS (Contact me in private)
2. go to uncompliant app and edit
3. try to edit, you will notice didnt save the changes.
4. try to eliminate the net config, same issue didnt save changes.

**Expected behavior**
Allows edit.
Not try to transform networking part (Vlans etc etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/8143984/214882957-bc5fc2ef-bfb0-4e3d-b4a6-bbf3abd83ff3.png)

contact me for more screenshots.

**Context**
Viprion rel 16, want to use github like a new Source of True

**Comment by f5-purc** [comment]
Filled for review MBIPMP-19501

**Comment by wojtek0806** [comment]
I have tested this on 4.1.0 and it allows me to edit part of non compliant files and i got the tenant to turn green:
![Screenshot 2024-03-20 at 14 55 40](https://github.com/f5devcentral/f5-journeys/assets/18006037/1021f97f-b203-4be8-8e2a-7323d76f4f2f)
Please retest with the latest 4.1.0 version (rebuild from scratch) and open a new issue using appropriate template providing sufficent data.
