### ISSUE TITLE
[FEAT] iSeries to rSeries upgrade

### ISSUE THREAD

**Issue by ekampmannf5** [f5devcentral/f5-journeys#98]
**Is your feature request related to a problem? Please describe.**
You take an iSeries source UCS and generate an destination UCS file for rSeries. I am missing the exact load sys ucs command for a sucessful import on the target device.

**Describe the solution you'd like**
Add something like this to the description:
When your source device was part of a HA cluster (most of the time), and the target device is already licensed (typical for F5OS targets), and you what to use the existing management IP of the new created target tenant, then you should use this command: 

tmsh load sys ucs <filename> platform-migrate no-license keep-current-management-ip reset-trust  

**Describe alternatives you've considered**

**Additional context**

**Comment by f5-purc** [comment]
filed internal MBIPMP-19499

**Comment by rmaliszewskif5** [comment]
Migration to rSeries is supported with 4.0.0 release.
